use_frameworks!

platform :ios, '10.0'

target 'GSScrollableLineChart_Example' do
  pod 'GSScrollableLineChart', :path => '../'

  target 'GSScrollableLineChart_Tests' do
    inherit! :search_paths

    
  end
end
